// Drivers for ADD/REMOVE/UPDATE for a given table
/*
! For midterm demo, focused on ADD a new issue

* add is just a "new" button/menu
? When adding with the "new" menu, separate entry by commas.
? This will NOT include the Issue ID, which will be generated by
? querying the database for the MAX value of ID and incrementing by
? one.

remove is a right click issue & delete button
update is a right click issue & edit button
*/

var { detectSqlKeywords, addToDatabase, queryHighestID } = require('./sql-helpers');

function parseAddInput(rawText){
    // remove all spaces from the given string.
    rawText = rawText.replace(/ /g, '');
    rawText = rawText + ',' + (queryHighestID() + 1);

    // split the rawText along a given delimiter (comma for now)
    // this will give us all our different parameters for the add function.
    //! Important that the parameters are in order for the midterm demo.
    //! Have tested queries ready to go.
    params = rawText.split(',');

    // Warn on keyword detection
    params.forEach(query => {
        let val = detectSqlKeywords(query);
    });

    // stick the comma delimited raw text into the add function.
    addToDatabase(rawText);
}

